/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.clase02.vista1;

import com.unab.logicaCalculadora.ClsOperacionesMat;

/**
 *
 * @author nelson
 */
public class EjemploCla extends javax.swing.JFrame {

    /**
     * Creates new form EjemploCla
     */
    public EjemploCla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtDato1 = new javax.swing.JTextField();
        TxtDato2 = new javax.swing.JTextField();
        TxtR = new javax.swing.JTextField();
        Lbldato1 = new javax.swing.JLabel();
        Lbldato2 = new javax.swing.JLabel();
        LblResultado = new javax.swing.JLabel();
        BtnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(51, 255, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TxtDato1.setBackground(new java.awt.Color(204, 102, 255));
        TxtDato1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TxtDato1.setForeground(new java.awt.Color(51, 0, 51));

        TxtDato2.setBackground(new java.awt.Color(204, 102, 255));
        TxtDato2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TxtDato2.setForeground(new java.awt.Color(51, 0, 51));

        TxtR.setEditable(false);
        TxtR.setBackground(new java.awt.Color(255, 153, 153));
        TxtR.setForeground(new java.awt.Color(51, 0, 51));

        Lbldato1.setBackground(new java.awt.Color(153, 0, 153));
        Lbldato1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        Lbldato1.setForeground(new java.awt.Color(204, 0, 0));
        Lbldato1.setText("DATO1");

        Lbldato2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Lbldato2.setForeground(new java.awt.Color(204, 0, 0));
        Lbldato2.setText("DATO2");

        LblResultado.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        LblResultado.setForeground(new java.awt.Color(153, 0, 153));
        LblResultado.setText("RESULTADO");

        BtnCalcular.setText("SUMAR");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lbldato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbldato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtDato1)
                    .addComponent(TxtR, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDato2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(BtnCalcular)
                .addGap(238, 238, 238))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDato1)
                    .addComponent(Lbldato1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDato2)
                    .addComponent(Lbldato2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtR)
                    .addComponent(LblResultado))
                .addGap(18, 18, 18)
                .addComponent(BtnCalcular)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        Double Dato1 = Double.parseDouble(TxtDato1.getText());
        Double Dato2 = Double.parseDouble(TxtDato2.getText());
        ClsOperacionesMat suma = new ClsOperacionesMat();
        Double r = suma.suma(Dato1, Dato2);
        TxtR.setText(r.toString());
        


    }//GEN-LAST:event_BtnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploCla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploCla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploCla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploCla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploCla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JLabel LblResultado;
    private javax.swing.JLabel Lbldato1;
    private javax.swing.JLabel Lbldato2;
    private javax.swing.JTextField TxtDato1;
    private javax.swing.JTextField TxtDato2;
    private javax.swing.JTextField TxtR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
